### PR TITLE
Added encode/decodeBytesForKey to the CMObjectEncoder/Decoder classes

### PR DESCRIPTION
**Pull request by natevecc**
This is an attempt to add `encodeBytesForKey` and `decodeBytesForKey` to the `CMObjectEncoder` and `CMObjectDecoder` classes respectfully. I'm using it in conjunction with the following [class](https://gist.github.com/natevecc/08fa725e151a16c804d3) to try and encode and decode `ORKResult` objects for use with ResearchKit.

Encoding appears to be working but decoding the response doesn't appear to be working correctly. Any advice would be greatly appreciated!

### CODE REVIEW

**Comment by ethanmick** [comment]
Thanks, I'll start taking a look!

**Comment by natevecc** [comment]
@ethanmick hey so I 'think' this is good now. I can upload and download objects defined [here](https://gist.github.com/natevecc/08fa725e151a16c804d3) and the data can be reused after downloading. The only thing that worries me is I get a lot of errors related to unrecognized selectors when decoding objects
```
2015-12-10 12:04:53.473 epic-rk[14445:287749] -[__NSCFString objectForKey:]: unrecognized selector sent to instance 0x7fe57bd84590
2015-12-10 12:04:53.474 epic-rk[14445:287749] -[__NSCFString objectForKey:]: unrecognized selector sent to instance 0x7fe57ba06de0
2015-12-10 12:04:53.474 epic-rk[14445:287749] -[__NSCFString objectForKey:]: unrecognized selector sent to instance 0x7fe57ba1f920
2015-12-10 12:04:53.474 epic-rk[14445:287749] -[__NSArrayM objectForKey:]: unrecognized selector sent to instance 0x7fe57ba44740
2015-12-10 12:04:53.474 epic-rk[14445:287749] -[__NSCFString objectForKey:]: unrecognized selector sent to instance 0x7fe57ba038f0
2015-12-10 12:04:53.474 epic-rk[14445:287749] -[__NSCFString objectForKey:]: unrecognized selector sent to instance 0x7fe57bd845d0
2015-12-10 12:04:53.475 epic-rk[14445:287749] -[__NSCFArray objectForKey:]: unrecognized selector sent to instance 0x7fe57b9055d0
2015-12-10 12:04:53.475 epic-rk[14445:287749] -[__NSCFString objectForKey:]: unrecognized selector sent to instance 0x7fe57ba0a800
2015-12-10 12:04:53.475 epic-rk[14445:287749] -[__NSCFString objectForKey:]: unrecognized selector sent to instance 0x7fe57ba0b4c0
2015-12-10 12:04:53.476 epic-rk[14445:287749] -[__NSCFString objectForKey:]: unrecognized selector sent to instance 0x7fe57964e9c0
2015-12-10 12:04:53.476 epic-rk[14445:287749] -[__NSCFString objectForKey:]: unrecognized selector sent to instance 0x7fe5796583b0
2015-12-10 12:04:53.476 epic-rk[14445:287749] -[__NSCFString objectForKey:]: unrecognized selector sent to instance 0x7fe579658720
2015-12-10 12:04:53.476 epic-rk[14445:287749] -[__NSCFString objectForKey:]: unrecognized selector sent to instance 0x7fe57ba0b960
```
I dug around in the code and it looks like this is how the SDK was designed: it chokes on objects that don't extend CMObject then eventually NSDecodes them. Wanted to know if this is expected or if I can do something to eliminate these errors.

**Comment by ethanmick** [comment]
Mostly expected, although annoying that the errors are logged. This looks good!

**Comment by ethanmick** [comment]
@natevecc I had a thought.

How are you going about in the CMObject serializing the UUID? Let's say I have a class:

```
// Header
@interface CMTestEncoderUUID : CMObject

@property (nonatomic, strong) NSUUID *uuid;

@end

// Implementation
@implementation CMTestEncoderUUID

- (instancetype)initWithCoder:(NSCoder *)aDecoder;
{
    if ( self = ([super initWithCoder:aDecoder]) ) {
        NSUInteger blockSize;
        const void* bytes = [aDecoder decodeBytesForKey:@"uuid" returnedLength:&blockSize];
        self.uuid = [[NSUUID alloc] initWithUUIDBytes:bytes];
    }
    return self;
}

- (void)encodeWithCoder:(NSCoder *)aCoder;
{
    [super encodeWithCoder:aCoder];
    uuid_t uuid;
    [self.uuid getUUIDBytes:uuid];
    [aCoder encodeBytes:uuid length:16 forKey:@"uuid"];
}

@end
```
When I serialize the UUID as bytes, I have to do quite a bit of legwork. And it works, you get the Base64 representation of the object. I wrote tests for it, so I'll probably add this anyways.

But doesn't it make more sense to store the UUID as a String?

```
// Implementation
@implementation CMTestEncoderUUID

- (instancetype)initWithCoder:(NSCoder *)aDecoder;
{
    if ( self = ([super initWithCoder:aDecoder]) ) {
        self.uuid = [[NSUUID alloc] initWithUUIDString:[aDecoder decodeObjectForKey:@"uuid"]];
    }
    return self;
}

- (void)encodeWithCoder:(NSCoder *)aCoder;
{
    [super encodeWithCoder:aCoder];
    [aCoder encodeObject:self.uuid.UUIDString forKey:@"uuid"];
}

@end
```

The iOS SDK doesn't know the difference between a String and a UUID, so we can't accept a UUID and serialize it to a String (Since once it's a String, how do we serialize it back? We could add this, but it would be a breaking change, 2.0).

Thoughts?

**Comment by natevecc** [comment]
@ethanmick I would have loved to encrypt/decrypt the UUID as a string but unfortunately NSUUID implements NSCoding itself.
```objc
// from: https://github.com/0xced/NSUUID/blob/master/NSUUID.m
// not the real implementation of NSUUID but I used it as the best representation I could find of what's
// going on under the hoood
- (id) initWithCoder:(NSCoder *)coder
{
	if ([coder allowsKeyedCoding])
	{
		NSUInteger length = 0;
		const uint8_t *uuid = [coder decodeBytesForKey:@"NS.uuidbytes" returnedLength:&length];
		if (length == sizeof(uuid_t))
		{
			return [self initWithUUIDBytes:uuid];
		}
		else
		{
			return [self init];
		}
	}
	else
	{
		@throw [NSException exceptionWithName:NSInvalidArgumentException reason:@"-[NSUUID initWithCoder]: NSUUIDs cannot be decoded by non-keyed coders" userInfo:nil];
	}
}

- (void) encodeWithCoder:(NSCoder *)coder
{
	if ([coder allowsKeyedCoding])
	{
		[coder encodeBytes:_uuid length:sizeof(_uuid) forKey:@"NS.uuidbytes"];
	}
	else
	{
		@throw [NSException exceptionWithName:NSInvalidArgumentException reason:@"-[NSUUID encodeWithCoder]: NSUUIDs cannot be encoded by non-keyed coders" userInfo:nil];
	}
}
```
It encodes/decodes it's data as bytes and ResearchKit uses that implementation instead of something I can give it that would just do strings.
```objc
// from ORKResult.m
- (void)encodeWithCoder:(NSCoder *)aCoder {
    [super encodeWithCoder:aCoder];
    ORK_ENCODE_OBJ(aCoder, taskRunUUID);
    ORK_ENCODE_URL(aCoder, outputDirectory);
}

- (instancetype)initWithCoder:(NSCoder *)aDecoder {
    self = [super initWithCoder:aDecoder];
    if (self) {
        ORK_DECODE_OBJ_CLASS(aDecoder, taskRunUUID, NSUUID);
        ORK_DECODE_URL(aDecoder, outputDirectory);
    }
    return self;
}
```
I figured going to/from a Base64 string was the best option unless there is some way to change ResearchKit's implementation to use a custom encoder/decoder or NSUUID implementation that uses strings. At one point I was going to try extending NSUUID but I don't think you can override methods with extensions.

Not sure about your last point. Here's an example of what's being stored in cloudmine generated from my code:
```JSON
{
	"result": {
		"outputDirectory": "Documents/",
		"endDate": {
			"__class__": "datetime",
			"timestamp": 1449766991.590622
		},
		"startDate": {
			"__class__": "datetime",
			"timestamp": 1449766851.071528
		},
		"taskRunUUID": {
			"NS.uuidbytes": "Ym4+WJ3bTDWn/BybOIHKqg==",
			"__class__": "__NSConcreteUUID"
		},
		"results": [
			{
				"results": [],
				"__class__": "ORKStepResult",
				"endDate": {
					"__class__": "datetime",
					"timestamp": 1449766856.83946
				},
				"startDate": {
					"__class__": "datetime",
					"timestamp": 1449766851.07095
				},
				"identifier": "IntroStep",
				"userInfo": null
			},
			{
				"results": [
					{
						"endDate": {
							"__class__": "datetime",
							"timestamp": 1449766991.590648
						},
						"startDate": {
							"__class__": "datetime",
							"timestamp": 1449766856.873825
						},
						"__class__": "ORKChoiceQuestionResult",
						"identifier": "TextChoiceQuestionStepUrinary1",
						"questionType": 2,
						"choiceAnswers": [
							2
						],
						"userInfo": null
					}
				],
				"__class__": "ORKStepResult",
				"endDate": {
					"__class__": "datetime",
					"timestamp": 1449766991.590648
				},
				"startDate": {
					"__class__": "datetime",
					"timestamp": 1449766856.873825
				},
				"identifier": "TextChoiceQuestionStepUrinary1",
				"userInfo": null
			}
		],
		"identifier": "SurveyTask",
		"__class__": "ORKTaskResult",
		"userInfo": null
	},
	"__access__": null,
	"__id__": "2E7F2CC0-4997-42BB-A792-AB06096DD0FE",
	"__class__": "epic_rk.CMORKTaskResult"
}
```
When it stores the NSUUID it has a `__class__` set to `__NSConcreteUUID` property that it uses to know which class to decode the data as. I think that's how the iOS SDK knows how to decode the string correctly. This should work for any class that calls the `encode/decodeBytes` methods since the JSON will always have them as base64 strings instead of regular strings.

**Comment by ethanmick** [comment]
Alright, Merged!

Could you use the lastest on Master and make sure it works as you'd expect?

Thanks!

**Comment by apbendi** [comment]
hey @natevecc, was doing some planning and ended up looking at this old PR.  Thanks a lot for submitting- its useful for all kinds of data someone might want to push to CloudMine. 

I see you submitted it in the context of storing NSUUIDs, which came up briefly on Wednesday. Take a look [here](https://github.com/cloudmine/CMHealthSDK-iOS/blob/master/Pod/Classes/Cocoa%2BCMHealth.m#L45) to see where I swizzle (aka :monkey: patch) the foundation class in the CMHealth SDK to encode itself using a string as opposed to the byte stream.

After some research it seems the likely reason Foundation uses bytes rather than strings by default is that it uses less space. I think in our case, that is not as big of a concern, and it seems to me the String version would be a lot easier to work with as a human if you're debugging something or writing a query to CloudMine backend. Here's what it looks like:

```json
"taskRunUUID": {
      "__class__": "__NSConcreteUUID",
      "UUIDString": "68789171-3229-403E-9A7C-8920544EFFDA"
    },
```

I'm thinking about introducing the swizzled method into the base SDK here, not just the CMHealth SDK. This would technically be a breaking change for anyone relying on this patch for serializing UUIDs. Given this was introduced recently, I doubt it's being relied upon by other customers (though I'll do some research). I wanted to get your feedback on possibly introducing it here, which would cause issues for you if you're trying to decode objects stored with the old schema. How big of a headache would that be for you? Is there still time for you to make the change before launching your app, or is it already frozen pending your pilot?

There also may be a way to introduce the change in a backwards compatible way. Will have to think through it a bit more. Thanks for your feedback!

**Pull request merged**
